version: '3.8'

services:
  app:
    build: .
    container_name: language-mentor
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
      - ./htmlcov:/app/htmlcov
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    command: python src/main.py

  test:
    build: .
    container_name: language-mentor-test
    volumes:
      - ./logs:/app/logs
      - ./htmlcov:/app/htmlcov
    command: python -m pytest tests/unit tests/integration --cov=src --cov-report=html --cov-report=term-missing 