name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lm
        python-version: '3.8'
        auto-activate-base: false
    
    - name: Install dependencies
      run: |
        conda activate lm
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: cmd /C CALL {0}
    
    - name: Run tests
      run: |
        conda activate lm
        pytest tests/unit --cov=src --cov-report=xml
        pytest tests/integration
      shell: cmd /C CALL {0}
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml 